development:
  adapter: postgresql
  encoding: unicode
  database: timetracker_disc_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: timetracker_disc_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: timetracker_disc_production
  pool: 5
  username: postgres
  password: postgres
